<a href="https://colab.research.google.com/github/kilianguillon/Cours_pytorch/blob/main/pytorch_cours.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

###Créer un tensor

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector=torch.tensor([7,7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [7]:
MATRIX=torch.tensor([[7,7],
 [8,8]])
MATRIX
MATRIX.ndim
MATRIX.shape

torch.Size([2, 2])

In [8]:
MATRIX[0]

tensor([7, 7])

In [9]:
TENSOR=torch.tensor([[[1,2,3],
            [5,6,7],
             [3,5,5]]])
TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [10]:
TENSOR.ndim

3

In [11]:
TENSOR[0]
TENSOR[0][2]
TENSOR[0][2][2]

tensor(5)

In [12]:
TENS=torch.tensor([[[1,2,3],[1,2,3]],[[4,2,3],[4,2,3]]])
TENS.shape

torch.Size([2, 2, 3])

In [13]:
TENS.ndim

3

In [14]:
zeros=torch.zeros((2,2))
zeros

tensor([[0., 0.],
        [0., 0.]])

In [15]:
ones=torch.ones((3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
ones.dtype

torch.float32

###Random tensors

In [17]:
random_tensor=torch.rand(2,2,3)
random_tensor

tensor([[[0.6776, 0.6336, 0.7499],
         [0.0739, 0.2207, 0.9757]],

        [[0.3639, 0.5110, 0.3374],
         [0.8170, 0.6441, 0.4422]]])

In [18]:
random_image_size=torch.rand(224,224,3  ) #hauteur, largeur, couleur
random_image_size.ndim, random_image_size.shape

(3, torch.Size([224, 224, 3]))

###Range and tensors-like

In [19]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
ranger=torch.arange(0,13,3)
ranger

tensor([ 0,  3,  6,  9, 12])

In [21]:
ranger_zeros=torch.zeros_like(ranger)
ranger_zeros

tensor([0, 0, 0, 0, 0])

###Tensor datatypes (cause d'erreurs) and devices

In [22]:
float_16_tensor=torch.tensor([30,6.0,9.0],dtype=torch.float16,
                             device=None,
                             requires_grad=False)
float_16_tensor.dtype

torch.float16

In [23]:
float_16_tensor.device

device(type='cpu')

### Manipulating tensors

In [24]:
a=torch.rand(2,2,2)
b=torch.rand(2,2,2)
a+10, a*10, a+b, a-b,a*b

(tensor([[[10.3643, 10.5561],
          [10.9724, 10.1533]],
 
         [[10.6421, 10.6321],
          [10.8450, 10.3956]]]),
 tensor([[[3.6429, 5.5612],
          [9.7243, 1.5327]],
 
         [[6.4214, 6.3209],
          [8.4496, 3.9563]]]),
 tensor([[[0.4509, 0.6029],
          [1.7322, 0.9389]],
 
         [[1.3894, 1.4575],
          [0.9037, 1.2351]]]),
 tensor([[[ 0.2777,  0.5094],
          [ 0.2127, -0.6323]],
 
         [[-0.1051, -0.1933],
          [ 0.7862, -0.4438]]]),
 tensor([[[0.0316, 0.0260],
          [0.7388, 0.1204]],
 
         [[0.4799, 0.5217],
          [0.0497, 0.3321]]]))

In [25]:
tensor = torch.arange(5)
print("element wise multiplication : "+str(tensor*tensor))
print("matrix multiplication : "+str(torch.matmul(tensor,tensor))) #ou torch.mm

element wise multiplication : tensor([ 0,  1,  4,  9, 16])
matrix multiplication : tensor(30)


In [26]:
tensor=torch.rand(2,2)
print(str(tensor))
print("matrix multiplication : "+str(torch.mm(tensor,tensor))) #plus efficace que faire des boucles (vectorised)

tensor([[0.0431, 0.1608],
        [0.0533, 0.2687]])
matrix multiplication : tensor([[0.0104, 0.0501],
        [0.0166, 0.0808]])


In [27]:
tensor=torch.rand(4,2)
tensor, tensor.T #transposition

(tensor([[0.6850, 0.4327],
         [0.8160, 0.6188],
         [0.7816, 0.5892],
         [0.6295, 0.1680]]),
 tensor([[0.6850, 0.8160, 0.7816, 0.6295],
         [0.4327, 0.6188, 0.5892, 0.1680]]))

### Finding min, max, mean, sum...


In [28]:
tensor=torch.arange(0,100,5)
tensor.min(), tensor.max(), tensor.mean(dtype=torch.float32), tensor.sum() #mean needs a float32 dtype (not 64)

(tensor(0), tensor(95), tensor(47.5000), tensor(950))

###Reshaping, stacking, squeezing and unsqueezing tensors

In [29]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [30]:
x_reshaped=x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [31]:
x_reshaped=x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [32]:
x = torch.arange(1.,11.)
x_reshaped=x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [33]:
z=x.view(1,10) #z shares the same memory as x (if z changes, x changes)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [34]:
z=x.view(2,5)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [35]:
z[:,0]=5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]))

In [36]:
x_stacked=torch.stack([x,x,x,x],dim=0) #stack par ligne
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]])

In [37]:
x_stacked=torch.stack([x,x,x,x],dim=1) #stack par colonne
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [38]:
x=torch.rand(1,9)
print(x, x.shape)
y=torch.squeeze(x) #it removes a dimension of x
print(y, y.shape)

tensor([[0.1214, 0.3700, 0.3567, 0.2761, 0.7764, 0.8146, 0.9356, 0.8173, 0.7863]]) torch.Size([1, 9])
tensor([0.1214, 0.3700, 0.3567, 0.2761, 0.7764, 0.8146, 0.9356, 0.8173, 0.7863]) torch.Size([9])


In [39]:
x=torch.rand(9)
print(x, x.shape)
y=torch.unsqueeze(x,dim=1) #it adds a dimension of x
print(y, y.shape)

tensor([0.8842, 0.7540, 0.8720, 0.5951, 0.3357, 0.0955, 0.7690, 0.1468, 0.1153]) torch.Size([9])
tensor([[0.8842],
        [0.7540],
        [0.8720],
        [0.5951],
        [0.3357],
        [0.0955],
        [0.7690],
        [0.1468],
        [0.1153]]) torch.Size([9, 1])


In [40]:
x=torch.randn(2,3,5) #permute crée une view de x donc utilise la même mémoire
x.size(),torch.permute(x,(2,0,1)).size()

(torch.Size([2, 3, 5]), torch.Size([5, 2, 3]))

In [41]:
#image example
x_original=torch.rand((224,224,3)) #(height, width, colour)
print(x_original.shape)
x_permuted=x_original.permute(2,0,1) #colour, height, width
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


###Indexation

In [42]:
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [43]:
x[0], x[0][1], x[0][1][2], x[:,2], x[:,:,1] # ":" means select all (it takes all the value of the Oth and 1st dim but only index 1 of the second ones)

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([4, 5, 6]),
 tensor(6),
 tensor([[7, 8, 9]]),
 tensor([[2, 5, 8]]))

###Pytorch and numpy

In [44]:
array = np.arange(1.,8.) #numpy en float64 et tensor en float32
tensor=torch.from_numpy(array) #deux emplacements mémoire différents
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [45]:
tensor = torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###Reproductibility

In [46]:
A=torch.rand(2,2)
B=torch.rand(2,2)
print(A==B)

tensor([[False, False],
        [False, False]])


In [47]:
torch.manual_seed(667)
A=torch.rand(2,2)
torch.manual_seed(667)
B=torch.rand(2,2)
print(A==B)

tensor([[True, True],
        [True, True]])


###GPU

In [50]:
torch.cuda.is_available() #vrai on a un gpu
device = 'cuda' if torch.cuda.is_available() else "cpu" #device agnostic variable
print(device, torch.cuda.device_count())

cuda 1


In [51]:
#putting tensors and models on gpu
tensor=torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [52]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [54]:
#a tensor on gpu can't transform to numpy
tensor_back_cpu=tensor_on_gpu.cpu()
tensor_back_cpu, tensor_back_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))