<a href="https://colab.research.google.com/github/kilianguillon/Cours_pytorch/blob/main/pytorch_cours.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

###Créer un tensor

In [ ]:
scalar = torch.tensor(7)
scalar

NameError: ignored

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

NameError: ignored

In [ ]:
vector=torch.tensor([7,7])
vector
vector.ndim
vector.shape

NameError: ignored

In [ ]:
MATRIX=torch.tensor([[7,7],
 [8,8]])
MATRIX
MATRIX.ndim
MATRIX.shape

NameError: ignored

In [ ]:
MATRIX[0]

NameError: ignored

In [ ]:
TENSOR=torch.tensor([[[1,2,3],
            [5,6,7],
             [3,5,5]]])
TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

NameError: ignored

In [ ]:
TENSOR[0]
TENSOR[0][2]
TENSOR[0][2][2]

NameError: ignored

In [ ]:
TENS=torch.tensor([[[1,2,3],[1,2,3]],[[4,2,3],[4,2,3]]])
TENS.shape

torch.Size([2, 2, 3])

In [ ]:
TENS.ndim

3

In [ ]:
zeros=torch.zeros((2,2))
zeros

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
ones=torch.ones((3,3))
ones

NameError: ignored

In [ ]:
ones.dtype

NameError: ignored

###Random tensors

In [ ]:
random_tensor=torch.rand(2,2,3)
random_tensor

tensor([[[0.5732, 0.6416, 0.7557],
         [0.3582, 0.9612, 0.6063]],

        [[0.9452, 0.6068, 0.8226],
         [0.6574, 0.6636, 0.7567]]])

In [ ]:
random_image_size=torch.rand(224,224,3  ) #hauteur, largeur, couleur
random_image_size.ndim, random_image_size.shape

(3, torch.Size([224, 224, 3]))

###Range and tensors-like

In [ ]:
torch.arange(0,10)

NameError: ignored

In [ ]:
ranger=torch.arange(0,13,3)
ranger

NameError: ignored

In [ ]:
ranger_zeros=torch.zeros_like(ranger)
ranger_zeros

NameError: ignored

###Tensor datatypes (cause d'erreurs) and devices

In [ ]:
float_16_tensor=torch.tensor([30,6.0,9.0],dtype=torch.float16,
                             device=None,
                             requires_grad=False)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor.device

device(type='cpu')

### Manipulating tensors

In [ ]:
a=torch.rand(2,2,2)
b=torch.rand(2,2,2)
a+10, a*10, a+b, a-b,a*b

(tensor([[[10.2704, 10.0693],
          [10.6460, 10.8935]],
 
         [[10.5735, 10.8008],
          [10.3531, 10.5812]]]),
 tensor([[[2.7036, 0.6932],
          [6.4602, 8.9351]],
 
         [[5.7350, 8.0080],
          [3.5309, 5.8123]]]),
 tensor([[[0.3638, 0.9870],
          [1.4903, 1.8893]],
 
         [[0.9869, 1.2272],
          [0.4026, 1.1787]]]),
 tensor([[[ 0.1769, -0.8484],
          [-0.1983, -0.1023]],
 
         [[ 0.1601,  0.3744],
          [ 0.3036, -0.0163]]]),
 tensor([[[0.0253, 0.0636],
          [0.5454, 0.8897]],
 
         [[0.2371, 0.3415],
          [0.0175, 0.3473]]]))